import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.scss";
import DashboardLayout from "@/app/components/dashboard-layout";
import {ToastProvider} from "@/app/components/providers/toast-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`
        ${geistSans.variable} 
        ${geistMono.variable} 
        antialiased
        bg-white text-black
        dark:bg-gray-900 dark:text-white
      `}
    >
    <ToastProvider>
      <DashboardLayout>
        {children}
      </DashboardLayout>
    </ToastProvider>
    </body>
    </html>
  );
}
